name = input()
sur_name = input()
Born = input()
print("#############################")
print("#  _  _ ___ _    _    ___   #")
print(r"# | || | __| |  | |  / _ \  #")
print("# | __ | _|| |__| |_| (_) | #")
print(r"# |_||_|___|____|____\___/  #")
print("#                           #")
print("#############################")
print("=============================")
print("My name is",name,sur_name)
print("My birthday is",Born)
print("You can call me ",name)
print("=============================")
